### ISSUE TITLE
Error on main page after upgrade from 1.7.1 to 1.8.0

### ISSUE THREAD

**Issue by ssurfertuga** [cryptosharks131/lndg#392]
After manually upgrading from 1.7.1 to 1.8.0 (I got no errors during the upgrade) I get this error on the homepage:

"Error Code: module 'lndg.settings' has no attribute 'LND_MAX_MESSAGE'"

<img width="606" alt="Screenshot 2024-08-07 at 14 30 58" src="https://github.com/user-attachments/assets/fae82cb4-f58c-4565-a80d-ce2481af4b9e">

OS: Ubuntu 22.04
LNDG: 1.8.0
Installation: Manual

**Comment by cryptosharks131** [comment]
Seems you are missing a parameter in your `settings.py` file that was introduced in `v1.7.1`. These steps will help you solve the issue.

Delete your settings.py file and re-initialize it **OR** add the required section manually in `lndg/settings.py`.
`rm lndg/settings.py`
`.venv/bin/python initialize.py`

#### OR

```
LND_MAX_MESSAGE = '35'
```

ref: https://github.com/cryptosharks131/lndg/releases/tag/v1.7.1

**Comment by ssurfertuga** [comment]
You're right. After I posted here I solved the problem by adding the LND_MAX_MESSAGE = '35' parameter in settings.py. I have another node that had the correct parameter after upgrading and using diff I got there.
However it would be interesting to understand why this parameter was not present after upgrading to 1.7.1 or 1.8.0.
